/* Machine generated file - edits will be overwritten. */

#ifndef FIO_CONFIG_MACRO
#define FIO_CONFIG_MACRO(...)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(ALWAYS_REBUILD_MD)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(ARCHIVE_NAND_COMMANDS)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(AUTO_ATTACH)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(AUTO_ATTACH_CACHE)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(BYPASS_ECC)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(BYPASS_WHITENING)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(CACHEBITS_DIFF2)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(COMPACTION_TIMEOUT_MS)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(DBGSET_COMPILE_DBGPRINT_OUT)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(DBGSET_LOCATIONS)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN) || defined(FIO_CONFIG_SET_DBGFLAG)
FIO_CONFIG_MACRO(DBGS_DIGEST)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN) || defined(FIO_CONFIG_SET_DBGFLAG)
FIO_CONFIG_MACRO(DBGS_DMA)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN) || defined(FIO_CONFIG_SET_DBGFLAG)
FIO_CONFIG_MACRO(DBGS_ECC)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN) || defined(FIO_CONFIG_SET_DBGFLAG)
FIO_CONFIG_MACRO(DBGS_GENERAL)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN) || defined(FIO_CONFIG_SET_DBGFLAG)
FIO_CONFIG_MACRO(DBGS_GROOM)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN) || defined(FIO_CONFIG_SET_DBGFLAG)
FIO_CONFIG_MACRO(DBGS_INJECT)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN) || defined(FIO_CONFIG_SET_DBGFLAG)
FIO_CONFIG_MACRO(DBGS_LOG_FILE)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN) || defined(FIO_CONFIG_SET_DBGFLAG)
FIO_CONFIG_MACRO(DBGS_LRBTREE)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN) || defined(FIO_CONFIG_SET_DBGFLAG)
FIO_CONFIG_MACRO(DBGS_MEDIA_ERROR)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN) || defined(FIO_CONFIG_SET_DBGFLAG)
FIO_CONFIG_MACRO(DBGS_METADATA)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN) || defined(FIO_CONFIG_SET_DBGFLAG)
FIO_CONFIG_MACRO(DBGS_PCIE)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN) || defined(FIO_CONFIG_SET_DBGFLAG)
FIO_CONFIG_MACRO(DBGS_PTRIM)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN) || defined(FIO_CONFIG_SET_DBGFLAG)
FIO_CONFIG_MACRO(DBGS_REQUEST)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN) || defined(FIO_CONFIG_SET_DBGFLAG)
FIO_CONFIG_MACRO(DBGS_SHOW_INJECT)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(DEEXTREMIFY)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(DEFAULT_FLASHBACK_MODE_ACTION)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(DEFAULT_MFR_BB_ALLOWANCE_HPCNT)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(DEFAULT_PACKET_SIZE)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(DISABLE_MSI)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(DISABLE_RLE)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(DONT_WHITEN)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(ECC_CORRECTION_PER_PAD_RETIRE)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(ECC_CORRECTION_RETIRE_THRESHOLD)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(ECC_CORRECTION_TARGET_THRESHOLD)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(ENABLE_CACHE_FILE)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(ENABLE_DISCARD)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(ENABLE_ECC)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(ENABLE_ECC_CHUNK_SHARE)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(ENABLE_ERROR_INJECTION)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(ENABLE_PCICHECK)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(ENABLE_PCIE_DEVICE_CONTROL_FIX)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(ENABLE_RANDOM_READ)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(ENABLE_TWO_PLANE)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN) || defined(FIO_CONFIG_SET_DBGFLAG)
FIO_CONFIG_MACRO(FIND_BUG_DA)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_STRING)
FIO_CONFIG_MACRO(FIO_BINDIR)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(FIO_CACHE_DITCH_THRESHOLD_1)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(FIO_CACHE_DITCH_THRESHOLD_2)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(FIO_CACHE_DITCH_THRESHOLD_3)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(FIO_CACHE_DITCH_THRESHOLD_4)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(FIO_COLLECT_RAW_STATS)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_STRING)
FIO_CONFIG_MACRO(FIO_DATADIR)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(FIO_DATA_GROOM_CONSIDER_IDLE_RATE)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(FIO_DATA_IDLE_GROOM_RATE)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(FIO_DEV_BLK_OPTIMAL_BLK_SIZE)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(FIO_DEV_WAIT_TIMEOUT_SECS)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_STRING)
FIO_CONFIG_MACRO(FIO_DOCDIR)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_STRING)
FIO_CONFIG_MACRO(FIO_DRIVER_NAME)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(FIO_FAIL_FAST)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(FIO_FORCE_SOFT_ECC)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(FIO_GC_DEFAULT_HIGH_WATER)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(FIO_GC_DEFAULT_LOW_WATER)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(FIO_GROOMER_DEFAULT_BLOCKS_PER)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(FIO_GROOMER_DEFAULT_DATA_PER)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(FIO_GROOMER_DEFAULT_MSG_BATCH_SIZE)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(FIO_GROOMER_DEFAULT_REQUEST_BATCH_SIZE)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(FIO_GROOMER_MAX_BLOCKS_PER)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(FIO_GROOMER_MAX_DATA_PER)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(FIO_GROOM_APPEND_POINT_RETRIES)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(FIO_GROOM_BUFFER_SIZE)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(FIO_GROOM_FAILING)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(FIO_GROOM_HARDER_THRESHOLD)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(FIO_GROOM_HARD_MAX_EXEMPT_BLOCKS)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(FIO_GROOM_OLDEST_LEB_COUNT)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(FIO_GROOM_OLDEST_LEB_INTERVAL)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(FIO_GROOM_POLL_INTERVAL)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(FIO_GROOM_SOFT_MAX_EXEMPT_BLOCKS)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(FIO_GROOM_VERIFY)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_STRING)
FIO_CONFIG_MACRO(FIO_INCLUDEDIR)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(FIO_INJECT_RECLAIM_PANIC)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_STRING)
FIO_CONFIG_MACRO(FIO_LIBDIR)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(FIO_LOG_FILE_PAGES)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(FIO_LRBTREE_ISEARCH_CUTOFF)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_STRING)
FIO_CONFIG_MACRO(FIO_MANDIR)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(FIO_METADATA_DEBUG_LRBTREE)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(FIO_METADATA_SWAP)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_STRING)
FIO_CONFIG_MACRO(FIO_OEM_DATADIR)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_STRING)
FIO_CONFIG_MACRO(FIO_OEM_LIBDIR)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_STRING)
FIO_CONFIG_MACRO(FIO_OEM_NAME)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_STRING)
FIO_CONFIG_MACRO(FIO_OEM_NAME_FORMAL)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_STRING)
FIO_CONFIG_MACRO(FIO_OEM_NAME_SHORT)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_STRING)
FIO_CONFIG_MACRO(FIO_OEM_SOURCEDIR)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(FIO_POWERCUT_DETECT)
#endif

#if defined(FIO_CONFIG_SET_INT_ARRAY) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(FIO_PREALLOCATE_MEMORY)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_STRING)
FIO_CONFIG_MACRO(FIO_PREFIX)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN) || defined(FIO_CONFIG_SET_DBGFLAG)
FIO_CONFIG_MACRO(FIO_PRINT_DANGLING)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN) || defined(FIO_CONFIG_SET_DBGFLAG)
FIO_CONFIG_MACRO(FIO_PRINT_DIGEST)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(FIO_PRINT_GROOM_STATS)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN) || defined(FIO_CONFIG_SET_DBGFLAG)
FIO_CONFIG_MACRO(FIO_PRINT_OBJECT)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(FIO_RESERVED_LEBS)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_STRING)
FIO_CONFIG_MACRO(FIO_SOURCEDIR)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_STRING)
FIO_CONFIG_MACRO(FIO_SYSCONFDIR)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(FLASHBACK_WARNING_AS_FAILURE)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(FORCE_ENABLE_PCIE_DEVICE_CONTROL_FIX)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(FORCE_MINIMAL_MODE)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(FORCE_SW_READ_COMPLETIONS)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(FUSION_ALLOCATION_TRIPWIRE)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_STRING)
FIO_CONFIG_MACRO(FUSION_BUILD_VERSION)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(FUSION_DEBUG)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(FUSION_DEBUG_CACHE)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(FUSION_DEBUG_MEMORY)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(FUSION_DEBUG_METADATA)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(FUSION_DIRECTFS)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(FUSION_DUMP_CMD_Q_ON_FAILURE)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(FUSION_INCLUDE_KTR)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_STRING)
FIO_CONFIG_MACRO(FUSION_MAJOR_VERSION)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(FUSION_METADATA_SAVE_WORST_CASE)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_STRING)
FIO_CONFIG_MACRO(FUSION_MICRO_VERSION)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_STRING)
FIO_CONFIG_MACRO(FUSION_MINOR_VERSION)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(FUSION_PACKET_SIZE_MAX)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(FUSION_PACKET_SIZE_MIN)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(FUSION_PACKET_SIZE_MUST_BE_POWER_OF_TWO)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(FUSION_SPARSEFS_SUPPORT)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(FUSION_SUPPORT_SIMULATED_DMA)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(FUSION_USE_SW_RESOURCE_ACCOUNTING)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(FUSION_VERIFY_FROB)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(FUSION_VERIFY_FROB_READONLY)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_STRING)
FIO_CONFIG_MACRO(FUSION_VERSION_STRING)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(GROOMER_BACKOFF)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(GROOMER_DISABLE)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(IODRIVE_ALLOW_1_2_7_FW)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(IODRIVE_DEAD_PAD_DETECTION_THRESHOLD)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(IODRIVE_DEAD_PAD_THRESHOLD)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(IODRIVE_DEBUG)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(IODRIVE_DEBUG_TRACK_ALL_REQUESTS)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(IODRIVE_DEFEAT_APPEND_RESERVATIONS)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(IODRIVE_DISABLE_PCIE_RELAXED_ORDERING)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(IODRIVE_DMA_DELAY)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(IODRIVE_GATHER_NAND_STATS)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(IODRIVE_GATHER_STATS)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(IODRIVE_INJECT_PAD_FAILURE_FREQUENCY)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(IODRIVE_ISR_READ_COMPLETIONS)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(IODRIVE_KTR_ENABLED)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(IODRIVE_LARGE_PCIE_MTU)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(IODRIVE_LOAD_EB_MAP)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(IODRIVE_LOAD_MIDPROM)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(IODRIVE_MAX_EBMAP_PROBE)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(IODRIVE_MAX_READ_THRESHOLD)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(IODRIVE_NUM_REQUEST_STRUCTURES)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(IODRIVE_PACKETIZER_INTERRUPT_THRESHOLD)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(IODRIVE_PRINT_CORRECTABLE_GROOMS)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(IODRIVE_READ_DMA_INTERRUPT_THRESHOLD)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(IODRIVE_READ_RETIRE_THRESHOLD)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(IODRIVE_READ_THRESHOLD_MLC_SCALING)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(IODRIVE_SCAN_NV_DATA)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(IODRIVE_SIMULATE_COMMAND_QUEUING_DMA)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(IODRIVE_SYNC_DELAY_US)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(IODRIVE_SYNC_REQUEST_DATA_DELAY_US)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(IODRIVE_SYNC_REQUEST_DATA_WAIT_US)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(IODRIVE_SYNC_WAIT_US)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(IODRIVE_TADDR0)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(IODRIVE_TADDR1)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(IODRIVE_TCMD0)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(IODRIVE_TCMD1)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(IODRIVE_THROTTLE_CAPACITY_WARNING_THRESHOLD)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(IODRIVE_THROTTLE_READ_ONLY_THRESHOLD)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(IODRIVE_THROTTLE_REDUCED_WRITE_THRESHOLD)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(IODRIVE_TINTR_HW_WAIT)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(IODRIVE_TREAD0)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(IODRIVE_TREAD1)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(IODRIVE_TREAD_HW_WAIT)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(IODRIVE_TREAD_HW_WAIT_MLC)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(IODRIVE_TSTAT_HW_WAIT)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(IODRIVE_TSTAT_HW_WAIT_MLC)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(IODRIVE_TWRITE0)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(IODRIVE_TWRITE1)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(IODRIVE_USE_COMMAND_TIMEOUTS)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(IODRIVE_USE_DPC)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(IODRIVE_USE_PAD_REMAP)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(IO_SCHEDULER_SWITCH_THRESHOLD)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(LOG_SCAN_YIELD_INTERVAL_MSECS)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(LRBTREE_PROFILE)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(LRB_DEBUG_MESSAGE)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(LRB_STATISTICS)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(MAX_MD_BLOCKS_PER_DEVICE)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(MEMOS_PREALLOCATED_OBJECTS)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(NUCLEON)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(NUM_EXCLUDE_DEVICES)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(NUM_INCLUDE_DEVICES)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(OVERRIDE_KTR_MASK)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(PARALLEL_ATTACH)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(PCIe_GLOBAL_SLOT_POWER_LIMIT)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(PERSISTENT_DISCARD)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(PIPELINE_ACCOUNTING)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN) || defined(FIO_CONFIG_SET_DBGFLAG)
FIO_CONFIG_MACRO(PRINT_APPEND_FAILURES)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN) || defined(FIO_CONFIG_SET_DBGFLAG)
FIO_CONFIG_MACRO(PRINT_APPEND_POINT)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN) || defined(FIO_CONFIG_SET_DBGFLAG)
FIO_CONFIG_MACRO(PRINT_DEPACKETIZER)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN) || defined(FIO_CONFIG_SET_DBGFLAG)
FIO_CONFIG_MACRO(PRINT_DMA)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN) || defined(FIO_CONFIG_SET_DBGFLAG)
FIO_CONFIG_MACRO(PRINT_DMA_READ)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN) || defined(FIO_CONFIG_SET_DBGFLAG)
FIO_CONFIG_MACRO(PRINT_DMA_WRITE)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN) || defined(FIO_CONFIG_SET_DBGFLAG)
FIO_CONFIG_MACRO(PRINT_ECC_READ)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN) || defined(FIO_CONFIG_SET_DBGFLAG)
FIO_CONFIG_MACRO(PRINT_ECC_WRITE)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN) || defined(FIO_CONFIG_SET_DBGFLAG)
FIO_CONFIG_MACRO(PRINT_GROOM_RANGES)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN) || defined(FIO_CONFIG_SET_DBGFLAG)
FIO_CONFIG_MACRO(PRINT_GROOM_SCAN)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN) || defined(FIO_CONFIG_SET_DBGFLAG)
FIO_CONFIG_MACRO(PRINT_IDLE_GROOM)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN) || defined(FIO_CONFIG_SET_DBGFLAG)
FIO_CONFIG_MACRO(PRINT_LEB_OPERATIONS)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN) || defined(FIO_CONFIG_SET_DBGFLAG)
FIO_CONFIG_MACRO(PRINT_NAND_READ)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN) || defined(FIO_CONFIG_SET_DBGFLAG)
FIO_CONFIG_MACRO(PRINT_NAND_READ_DETAILS)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN) || defined(FIO_CONFIG_SET_DBGFLAG)
FIO_CONFIG_MACRO(PRINT_NAND_WRITE)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN) || defined(FIO_CONFIG_SET_DBGFLAG)
FIO_CONFIG_MACRO(PRINT_PACKETIZER)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN) || defined(FIO_CONFIG_SET_DBGFLAG)
FIO_CONFIG_MACRO(PRINT_PARITY_OPERATIONS)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN) || defined(FIO_CONFIG_SET_DBGFLAG)
FIO_CONFIG_MACRO(PRINT_PROGRESS)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN) || defined(FIO_CONFIG_SET_DBGFLAG)
FIO_CONFIG_MACRO(PRINT_REATTACH)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN) || defined(FIO_CONFIG_SET_DBGFLAG)
FIO_CONFIG_MACRO(PRINT_REQUESTS)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN) || defined(FIO_CONFIG_SET_DBGFLAG)
FIO_CONFIG_MACRO(PRINT_REQUEST_LIST)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN) || defined(FIO_CONFIG_SET_DBGFLAG)
FIO_CONFIG_MACRO(PRINT_RESOURCES)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN) || defined(FIO_CONFIG_SET_DBGFLAG)
FIO_CONFIG_MACRO(PRINT_SCAN)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN) || defined(FIO_CONFIG_SET_DBGFLAG)
FIO_CONFIG_MACRO(PRINT_SCAN_ENTRIES)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(REGISTER_AS_CCISS)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(SPINLOCK_STATS)
#endif

#if defined(FIO_CONFIG_SET_INT) || defined(FIO_CONFIG_SET_ALL)
FIO_CONFIG_MACRO(STRICT_SYNC)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(SUPPORT_DUMP)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(SUPPORT_HIBERNATION)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(THERMAL_THROTTLE_DISABLE)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(USE_LARGE_PCIE_RX_BUFFER)
#endif

#if defined(FIO_CONFIG_SET_ALL) || defined(FIO_CONFIG_SET_BOOLEAN)
FIO_CONFIG_MACRO(USE_NEW_IO_SCHED)
#endif
