/* -----------------------------------------------------------------------------
 * Copyright (c) 2017, Fusion-io, Inc. (acquired by SanDisk Corp. 2014)
 * Copyright (c) 2014 SanDisk Corp. and/or all its affiliates.
 * All rights reserved.
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * * Redistributions of source code must retain the above copyright notice,
 *   this list of conditions and the following disclaimer.
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 * * Neither the name of the SanDisk Corp. nor the names of its contributors
 *   may be used to endorse or promote products derived from this software
 *   without specific prior written permission.
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
 * OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 * OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * ---------------------------------------------------------------------------*/

/* Machine generated file - edits will be overwritten. */

#ifndef FIO_PORT_CONFIG_MACRO
#define FIO_PORT_CONFIG_MACRO(...)
#endif

#if defined(FIO_PORT_CONFIG_SET_INT) || defined(FIO_PORT_CONFIG_SET_ALL)
FIO_PORT_CONFIG_MACRO(FIO_CACHE_DITCH_THRESHOLD_1)
#endif

#if defined(FIO_PORT_CONFIG_SET_INT) || defined(FIO_PORT_CONFIG_SET_ALL)
FIO_PORT_CONFIG_MACRO(FIO_CACHE_DITCH_THRESHOLD_2)
#endif

#if defined(FIO_PORT_CONFIG_SET_INT) || defined(FIO_PORT_CONFIG_SET_ALL)
FIO_PORT_CONFIG_MACRO(FIO_CACHE_DITCH_THRESHOLD_3)
#endif

#if defined(FIO_PORT_CONFIG_SET_INT) || defined(FIO_PORT_CONFIG_SET_ALL)
FIO_PORT_CONFIG_MACRO(FIO_CACHE_DITCH_THRESHOLD_4)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_STRING)
FIO_PORT_CONFIG_MACRO(FIO_OEM_SOURCEDIR)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_BOOLEAN)
FIO_PORT_CONFIG_MACRO(KFIO_SCSI_DEVICE)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_STRING)
FIO_PORT_CONFIG_MACRO(FIO_DATADIR)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_STRING)
FIO_PORT_CONFIG_MACRO(FUSION_MAJOR_VERSION)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_BOOLEAN)
FIO_PORT_CONFIG_MACRO(DISABLE_EXPORTED_SYMBOLS)
#endif

#if defined(FIO_PORT_CONFIG_SET_INT) || defined(FIO_PORT_CONFIG_SET_ALL)
FIO_PORT_CONFIG_MACRO(STRICT_SYNC)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_BOOLEAN)
FIO_PORT_CONFIG_MACRO(PORT_SUPPORTS_PCI_NUMA_INFO)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_BOOLEAN)
FIO_PORT_CONFIG_MACRO(DISABLE_MSIX)
#endif

#if defined(FIO_PORT_CONFIG_SET_INT) || defined(FIO_PORT_CONFIG_SET_ALL)
FIO_PORT_CONFIG_MACRO(FIO_GROOM_MAX_BUFFER_SIZE)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_BOOLEAN)
FIO_PORT_CONFIG_MACRO(BYPASS_ECC)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_STRING)
FIO_PORT_CONFIG_MACRO(FIO_OEM_DATADIR)
#endif

#if defined(FIO_PORT_CONFIG_SET_INT) || defined(FIO_PORT_CONFIG_SET_ALL)
FIO_PORT_CONFIG_MACRO(FIO_DATA_GROOM_CONSIDER_IDLE_RATE)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_STRING)
FIO_PORT_CONFIG_MACRO(FIO_DRIVER_NAME)
#endif

#if defined(FIO_PORT_CONFIG_SET_INT) || defined(FIO_PORT_CONFIG_SET_ALL)
FIO_PORT_CONFIG_MACRO(IODRIVE_SYNC_WAIT_US)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_BOOLEAN)
FIO_PORT_CONFIG_MACRO(FUSION_DEBUG_MEMORY)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_BOOLEAN)
FIO_PORT_CONFIG_MACRO(PORT_SUPPORTS_NUMA_NODE_OVERRIDE)
#endif

#if defined(FIO_PORT_CONFIG_SET_INT) || defined(FIO_PORT_CONFIG_SET_ALL)
FIO_PORT_CONFIG_MACRO(GROOMER_LOW_WATER_DELTA_HPCNT)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_BOOLEAN)
FIO_PORT_CONFIG_MACRO(DISABLE_SCANNER)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_STRING)
FIO_PORT_CONFIG_MACRO(FIO_MANDIR)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_BOOLEAN)
FIO_PORT_CONFIG_MACRO(IODRIVE_USE_COMMAND_TIMEOUTS)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_BOOLEAN)
FIO_PORT_CONFIG_MACRO(FUSION_COVERAGE)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_BOOLEAN)
FIO_PORT_CONFIG_MACRO(USE_LARGE_PCIE_RX_BUFFER)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_STRING)
FIO_PORT_CONFIG_MACRO(FIO_DOCDIR)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_BOOLEAN)
FIO_PORT_CONFIG_MACRO(FUSION_INTERNAL)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_BOOLEAN)
FIO_PORT_CONFIG_MACRO(FORCE_ENABLE_PCIE_DEVICE_CONTROL_FIX)
#endif

#if defined(FIO_PORT_CONFIG_SET_INT) || defined(FIO_PORT_CONFIG_SET_ALL)
FIO_PORT_CONFIG_MACRO(RSORT_MEMORY_LIMIT_MiB)
#endif

#if defined(FIO_PORT_CONFIG_SET_INT) || defined(FIO_PORT_CONFIG_SET_ALL)
FIO_PORT_CONFIG_MACRO(DEFAULT_LINUX_MAX_NR_REQUESTS)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_BOOLEAN)
FIO_PORT_CONFIG_MACRO(FIO_FAIL_FAST)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_STRING)
FIO_PORT_CONFIG_MACRO(FIO_AFFINITY)
#endif

#if defined(FIO_PORT_CONFIG_SET_INT) || defined(FIO_PORT_CONFIG_SET_ALL)
FIO_PORT_CONFIG_MACRO(IODRIVE_THROTTLE_CAPACITY_WARNING_THRESHOLD)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_BOOLEAN)
FIO_PORT_CONFIG_MACRO(FIO_SCSI_UNMAP_SUPPORTED)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_BOOLEAN)
FIO_PORT_CONFIG_MACRO(PORT_SUPPORTS_NUMA_NODE_CACHE_ALLOCATIONS)
#endif

#if defined(FIO_PORT_CONFIG_SET_INT) || defined(FIO_PORT_CONFIG_SET_ALL)
FIO_PORT_CONFIG_MACRO(LOG_SCAN_YIELD_INTERVAL_MSECS)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_BOOLEAN)
FIO_PORT_CONFIG_MACRO(FIO_QOS_ENABLE)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_STRING)
FIO_PORT_CONFIG_MACRO(FIO_BINDIR)
#endif

#if defined(FIO_PORT_CONFIG_SET_INT) || defined(FIO_PORT_CONFIG_SET_ALL)
FIO_PORT_CONFIG_MACRO(FIO_DEV_WAIT_TIMEOUT_SECS)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_BOOLEAN)
FIO_PORT_CONFIG_MACRO(IODRIVE_LOAD_EB_MAP)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_BOOLEAN)
FIO_PORT_CONFIG_MACRO(USE_NEW_IO_SCHED)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_STRING)
FIO_PORT_CONFIG_MACRO(FIO_LIBDIR)
#endif

#if defined(FIO_PORT_CONFIG_SET_INT) || defined(FIO_PORT_CONFIG_SET_ALL)
FIO_PORT_CONFIG_MACRO(GROOMER_HIGH_WATER_DELTA_HPCNT)
#endif

#if defined(FIO_PORT_CONFIG_SET_INT) || defined(FIO_PORT_CONFIG_SET_ALL)
FIO_PORT_CONFIG_MACRO(FIO_GROOM_POLL_INTERVAL)
#endif

#if defined(FIO_PORT_CONFIG_SET_INT) || defined(FIO_PORT_CONFIG_SET_ALL)
FIO_PORT_CONFIG_MACRO(PREALLOCATE_MB)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_STRING)
FIO_PORT_CONFIG_MACRO(EXCLUDE_DEVICES)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_BOOLEAN)
FIO_PORT_CONFIG_MACRO(PORT_SUPPORTS_USER_PAGES)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_BOOLEAN)
FIO_PORT_CONFIG_MACRO(PARALLEL_ATTACH)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_BOOLEAN)
FIO_PORT_CONFIG_MACRO(FUSION_DEBUG_CACHE)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_BOOLEAN)
FIO_PORT_CONFIG_MACRO(ENABLE_ECC)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_STRING)
FIO_PORT_CONFIG_MACRO(FUSION_VERSION)
#endif

#if defined(FIO_PORT_CONFIG_SET_INT) || defined(FIO_PORT_CONFIG_SET_ALL)
FIO_PORT_CONFIG_MACRO(RMAP_MEMORY_LIMIT_MiB)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_BOOLEAN)
FIO_PORT_CONFIG_MACRO(ENABLE_ERROR_INJECTION)
#endif

#if defined(FIO_PORT_CONFIG_SET_INT) || defined(FIO_PORT_CONFIG_SET_ALL)
FIO_PORT_CONFIG_MACRO(EXPECTED_IO_SIZE)
#endif

#if defined(FIO_PORT_CONFIG_SET_INT) || defined(FIO_PORT_CONFIG_SET_ALL)
FIO_PORT_CONFIG_MACRO(FIO_DATA_IDLE_GROOM_RATE)
#endif

#if defined(FIO_PORT_CONFIG_SET_INT) || defined(FIO_PORT_CONFIG_SET_ALL)
FIO_PORT_CONFIG_MACRO(IODRIVE_TINTR_HW_WAIT)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_BOOLEAN)
FIO_PORT_CONFIG_MACRO(IODRIVE_LOAD_MIDPROM)
#endif

#if defined(FIO_PORT_CONFIG_SET_INT) || defined(FIO_PORT_CONFIG_SET_ALL)
FIO_PORT_CONFIG_MACRO(AUTO_ATTACH_CACHE)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_BOOLEAN)
FIO_PORT_CONFIG_MACRO(RETIRE_ON_PSUB)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_BOOLEAN)
FIO_PORT_CONFIG_MACRO(IODRIVE_DISABLE_PCIE_RELAXED_ORDERING)
#endif

#if defined(FIO_PORT_CONFIG_SET_INT) || defined(FIO_PORT_CONFIG_SET_ALL)
FIO_PORT_CONFIG_MACRO(USE_MODULES)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_STRING)
FIO_PORT_CONFIG_MACRO(FIO_SOURCEDIR)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_BOOLEAN)
FIO_PORT_CONFIG_MACRO(FUSION_STATIC_KERNEL)
#endif

#if defined(FIO_PORT_CONFIG_SET_INT) || defined(FIO_PORT_CONFIG_SET_ALL)
FIO_PORT_CONFIG_MACRO(FIO_GROOM_HARDER_THRESHOLD)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_BOOLEAN)
FIO_PORT_CONFIG_MACRO(IODRIVE_MAKE_ASSERT_NONFATAL)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_BOOLEAN)
FIO_PORT_CONFIG_MACRO(PORT_SUPPORTS_SGLIST_COPY)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_BOOLEAN)
FIO_PORT_CONFIG_MACRO(ENABLE_DISCARD)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_STRING)
FIO_PORT_CONFIG_MACRO(FIO_SYSCONFDIR)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_BOOLEAN)
FIO_PORT_CONFIG_MACRO(MAX_MD_BLOCKS_PER_DEVICE)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_BOOLEAN)
FIO_PORT_CONFIG_MACRO(ENABLE_PCIE_DEVICE_CONTROL_FIX)
#endif

#if defined(FIO_PORT_CONFIG_SET_INT) || defined(FIO_PORT_CONFIG_SET_ALL)
FIO_PORT_CONFIG_MACRO(FIO_GROOM_OLDEST_LEB_INTERVAL)
#endif

#if defined(FIO_PORT_CONFIG_SET_INT) || defined(FIO_PORT_CONFIG_SET_ALL)
FIO_PORT_CONFIG_MACRO(FIO_GROOM_OLDEST_LEB_COUNT)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_BOOLEAN)
FIO_PORT_CONFIG_MACRO(FIO_FORCE_SOFT_ECC)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_BOOLEAN)
FIO_PORT_CONFIG_MACRO(PORT_SUPPORTS_PER_CPU)
#endif

#if defined(FIO_PORT_CONFIG_SET_INT) || defined(FIO_PORT_CONFIG_SET_ALL)
FIO_PORT_CONFIG_MACRO(IODRIVE_NUM_REQUEST_STRUCTURES)
#endif

#if defined(FIO_PORT_CONFIG_SET_INT) || defined(FIO_PORT_CONFIG_SET_ALL)
FIO_PORT_CONFIG_MACRO(PCIe_GLOBAL_SLOT_POWER_LIMIT)
#endif

#if defined(FIO_PORT_CONFIG_SET_INT) || defined(FIO_PORT_CONFIG_SET_ALL)
FIO_PORT_CONFIG_MACRO(READ_PIPE_DEPTH)
#endif

#if defined(FIO_PORT_CONFIG_SET_INT) || defined(FIO_PORT_CONFIG_SET_ALL)
FIO_PORT_CONFIG_MACRO(FIO_GROOM_HARD_MAX_EXEMPT_BLOCKS)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_BOOLEAN)
FIO_PORT_CONFIG_MACRO(FORCE_MINIMAL_MODE)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_STRING)
FIO_PORT_CONFIG_MACRO(FUSION_MINOR_VERSION)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_STRING)
FIO_PORT_CONFIG_MACRO(FIO_OEM_LIBDIR)
#endif

#if defined(FIO_PORT_CONFIG_SET_INT) || defined(FIO_PORT_CONFIG_SET_ALL)
FIO_PORT_CONFIG_MACRO(AUTO_ATTACH)
#endif

#if defined(FIO_PORT_CONFIG_SET_INT) || defined(FIO_PORT_CONFIG_SET_ALL)
FIO_PORT_CONFIG_MACRO(IODRIVE_SYNC_DELAY_US)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_STRING)
FIO_PORT_CONFIG_MACRO(FIO_EXTERNAL_POWER_OVERRIDE)
#endif

#if defined(FIO_PORT_CONFIG_SET_INT) || defined(FIO_PORT_CONFIG_SET_ALL)
FIO_PORT_CONFIG_MACRO(COMPACTION_TIMEOUT_MS)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_BOOLEAN)
FIO_PORT_CONFIG_MACRO(GROOMER_DISABLE)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_BOOLEAN)
FIO_PORT_CONFIG_MACRO(FUSION_MANGLE_RELEASE_SYMBOLS)
#endif

#if defined(FIO_PORT_CONFIG_SET_INT) || defined(FIO_PORT_CONFIG_SET_ALL)
FIO_PORT_CONFIG_MACRO(FIO_GROOM_BUFFER_SIZE)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_STRING)
FIO_PORT_CONFIG_MACRO(FIO_OEM_NAME)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_STRING)
FIO_PORT_CONFIG_MACRO(FIO_INCLUDEDIR)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_BOOLEAN)
FIO_PORT_CONFIG_MACRO(FUSION_DEBUG)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_STRING)
FIO_PORT_CONFIG_MACRO(INCLUDE_DEVICES)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_STRING)
FIO_PORT_CONFIG_MACRO(FIO_PREALLOCATE_MEMORY)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_STRING)
FIO_PORT_CONFIG_MACRO(FIO_PREFIX)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_STRING)
FIO_PORT_CONFIG_MACRO(FIO_OEM_NAME_SHORT)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_BOOLEAN)
FIO_PORT_CONFIG_MACRO(FIO_GROOM_LOG_LBA_IN_FAILED_LEB)
#endif

#if defined(FIO_PORT_CONFIG_SET_INT) || defined(FIO_PORT_CONFIG_SET_ALL)
FIO_PORT_CONFIG_MACRO(FIO_DEV_BLK_OPTIMAL_BLK_SIZE)
#endif

#if defined(FIO_PORT_CONFIG_SET_INT) || defined(FIO_PORT_CONFIG_SET_ALL)
FIO_PORT_CONFIG_MACRO(IODRIVE_MAX_EBMAP_PROBE)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_BOOLEAN)
FIO_PORT_CONFIG_MACRO(DISABLE_MSI)
#endif

#if defined(FIO_PORT_CONFIG_SET_INT) || defined(FIO_PORT_CONFIG_SET_ALL)
FIO_PORT_CONFIG_MACRO(KFIO_SCSI_QUEUE_DEPTH)
#endif

#if defined(FIO_PORT_CONFIG_SET_INT) || defined(FIO_PORT_CONFIG_SET_ALL)
FIO_PORT_CONFIG_MACRO(FIO_GROOM_SOFT_MAX_EXEMPT_BLOCKS)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_BOOLEAN)
FIO_PORT_CONFIG_MACRO(DISABLE_MODULE_PARAM_EXPORT)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_STRING)
FIO_PORT_CONFIG_MACRO(FUSION_MICRO_VERSION)
#endif

#if defined(FIO_PORT_CONFIG_SET_ALL) || defined(FIO_PORT_CONFIG_SET_STRING)
FIO_PORT_CONFIG_MACRO(FIO_OEM_NAME_FORMAL)
#endif
